DATALOADER:
  ASPECT_RATIO_GROUPING: True
MODEL:
  META_ARCHITECTURE: "build_flowsetnet"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  FLOWSETNET:
    IN_FEATURES: ["res5"]
    CODE_CHANNELS: 512
    DECODER_TYPE: "MLP"
    GNN_ITERATION: 1
    EMBEDDING_TYPE: "PAIR_WISE"
    TARGET: "BOX"
    ELEMENT_DIM: 4
    MAX_ELEMENT_NUM: 20
    LOSS_FUNCTION: 'EUCLIDEAN'
    SMOOTH_L1_BETA: 1.0
    SCORE_THRESH_TEST: 0.5
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00001
  STEPS: (50000, 100000)
  MAX_ITER: 100000
